[build]
command = "pnpm install && pnpm run build"
output_directory = ".next"
base_directory = "apps/web"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"

# Add main entry point for Wrangler
main = ".next/standalone/server.js"

# Configure Pages Functions
[functions]
directory = ".next/server/pages"
include = ["apps/web/.next/server/pages/**/*.js"]
exclude = ["node_modules/**/*", ".git/**/*"]

[env.production]
name = "gnatt-site-production"

[env.preview]
name = "gnatt-site-preview" 