[build]
command = "pnpm install && pnpm run build"
output_directory = ".next"
base_directory = "apps/web"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"

# Add main entry point for Wrangler
main = "worker.js"

# Configure compatibility
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment-specific settings
[env.production]
name = "site"

[env.preview]
name = "site-preview"

# Configure Pages Functions
[functions]
directory = ".next/server/pages"
include = ["apps/web/.next/server/pages/**/*.js"]
exclude = ["node_modules/**/*", ".git/**/*"] 