[build]
command = "pnpm install && pnpm run build"
output_directory = ".next"
base_directory = "apps/web"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"

[env.production]
name = "gnatt-site-production"

[env.preview]
name = "gnatt-site-preview" 