# Root wrangler.toml that redirects to the app's entry point
name = "site"
main = "apps/web/worker.js"

compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Use the app's configuration
[build]
command = "cd apps/web && pnpm install && pnpm run build"
output_directory = "apps/web/.next"

[build.environment]
NODE_VERSION = "18"

# Define how assets are served
[site]
bucket = "apps/web/.next" 